### ISSUE TITLE
Moar Updates

### ISSUE THREAD

**Issue by smudge202** [herecydev/TestAttributes#32]
If I create a new `XUnit Test Project` in VS2015 (either it was a built in template or came with SideWaffle) the `project.json` is as follows:

```json
  "dependencies": {
    "xunit": "2.1.0-beta4-build3109",
    "xunit.runner.dnx": "2.1.0-beta4-build134"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },

  "frameworks" : {
    "dnx451": { },
    "dnxcore50" : {
      "dependencies": {
        "Microsoft.CSharp": "4.0.0-beta-22816",
        "System.Collections": "4.0.10-beta-22816",
        "System.Linq": "4.0.0-beta-22816",
        "System.Threading": "4.0.10-beta-22816"
      }
    }
  }
```

Can we get test attributes brought inline with those xunit/runner builds please? (Might do this myself and PR but no promises)

**Comment by herecydev** [comment]
Will take a look at it shortly.

**Comment by smudge202** [comment]
I tried to override the `TestAttributes` dependencies by specifying the above xunit builds but it just silently fails to discover/run tests. Hopefully the only change required is to the TestAttributes `project.json` dependencies?

**Comment by herecydev** [comment]
Right, I'm running into some fundamentally broken things that are throwing me off. Firstly, incomplete nuget packages, that due to caching, aren't resolving at all. Secondly, the dependency graph doesn't appear to be resolved correctly, possibly [this](https://github.com/xunit/xunit/issues/545). So I'm forcing this myself.

Also just had some ridiculous dependencies on `Microsoft.Framework.DependencyInjection.*`, which were lurking in the `project.lock.json`. Deleted this and build again to solve, I thought that's what rebuild does?

I'm getting somewhere but this is not so much fun :rage:

**Comment by smudge202** [comment]
Damn, that doesn't look fun at all. Sorry I missed your call, Grandad nap....
